export enum StatusTransporte {
  AGUARDANDO_SEPARACAO = 'AGUARDANDO_SEPARACAO',
  EM_SEPARACAO = 'EM_SEPARACAO',
  SEPARACAO_CONCLUIDA = 'SEPARACAO_CONCLUIDA',
  EM_CONFERENCIA = 'EM_CONFERENCIA',
  CONFERENCIA_CONCLUIDA = 'CONFERENCIA_CONCLUIDA',
  EM_CARREGAMENTO = 'EM_CARREGAMENTO',
  CARREGAMENTO_CONCLUIDO = 'CARREGAMENTO_CONCLUIDO',
  FATURADO = 'FATURADO',
  LIBERADO_PORTARIA = 'LIBERADO_PORTARIA',
  CANCELADO = 'CANCELADO',
}
